Django/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog, name='home'),
    path('<int:post_id>/', views.post, name='post'),
]

Django/home/urls.py
from django.urls import path
from . import views

app_name = 'home'


urlpatterns = [
    path('', views.home, name='home'),
]

Django/project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

Django/blog/models.py
from django.db import models

# Create your models here.

Django/home/models.py
from django.db import models

# Create your models here.

Django/blog/views.py
from django.shortcuts import render
from django.http import Http404

from blog.data import posts


# Create your views here.
def blog(request):
    print('blog')

    context = {
        # 'text': 'My blog!',
        'title': 'Blog - ',
        'posts': posts,
    }

    return render(
        request,
        'blog/index.html',
        context,
    )


def post(request, post_id):
    found_post = None

    for post in posts:
        if post['id'] == post_id:
            found_post = post
            break

    if found_post is None:
        raise Http404("Post does not exist")

    context = {
        # 'text': 'My blog!',
        'title': 'Blog - ',
        'post': found_post
    }

    return render(
        request,
        'blog/post.html',
        context,
    )

Django/home/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
    print('home')

    context = {
        'text': 'Welcome to home!',
        'title': 'Home - '
    }

    return render(
        request,
        'home/index.html',
        context,
    )

Django/blog/templates/blog/index.html
{% extends 'global/base.html' %}

{% block text %} {{ text }} {% endblock text %}

{% block posts %}
  {% for post in posts %}
    {% include 'global/partials/postblock.html' %}
  {% endfor %}
{% endblock posts %}

Django/blog/templates/blog/post.html
{% extends 'global/base.html' %}

{% block text %} {{ text }} {% endblock text %}

{% block posts %}
  <article class="post single-post">
    <header>
      <h1 class="post__title">
        <a href="{% url 'blog:post' post.id %}">
          {{ post.title }}
        </a>
      </h1>
    </header>
    <div class="post__body">
      {{ post.body }}
    </div>
  </article>
{% endblock posts %}

Django/home/templates/home/index.html
{% extends 'global/base.html' %}

{% block text %} {{ text }} {% endblock text %}